name: Go
on: [push, pull_request]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - name: Install linters
        run: |
          go get -u github.com/mgechev/revive@v1.0.1
          go get golang.org/x/tools/cmd/goimports

      - name: goimports
        run: goimports -d .
      - name: revive
        run: revive -config revive.toml ./...


  build:
    name: Build
    runs-on: ubuntu-latest
    needs : [lint]
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - uses: actions/checkout@v2

      - name: Build
        run: go build -v .
