name: Go
on:
  push:
    branches: [master]
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - run: go get golang.org/x/tools/cmd/goimports
      - run: go get -u github.com/mgechev/revive@v1.0.1

      - uses: actions/checkout@v2

      - run: goimports -d .
      - run: revive -config revive.toml ./...


  build:
    name: Build
    runs-on: ubuntu-latest
    needs : [lint]
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - uses: actions/checkout@v2

      - name: Build
        run: go build -v .
