name: Go
on:
  push:
    branches: [master]
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: setup environment
        run: echo "::add-path::$(go env GOPATH)/bin"

      - name: install linters
        uses: actions/cache@v1
        id: cache-linters
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-linters
          restore-keys: |
            ${{ runner.os }}-linters


      - name: install linters
        run: |
          go get \
            golang.org/x/tools/cmd/goimports \
            github.com/mgechev/revive
        if: steps.cache-linters.outputs.cache-hit != 'true'

      - name: check out code
        uses: actions/checkout@v2

      - name: goimports
        run: goimports -d .
      - name: revive
        run: revive -config revive.toml ./...


  build:
    name: Build
    runs-on: ubuntu-latest
    needs : [lint]
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - uses: actions/checkout@v2

      - name: build
        run: go build -v .
